language: php
env:
    #- CODECEPTION_VERSION="1.6"
    #- CODECEPTION_VERSION="1.7"
    #- CODECEPTION_VERSION="1.8"
    - CODECEPTION_VERSION="2.0"
    - CODECEPTION_VERSION="dev-master"
php:
  - 5.5
  - 5.4
  #- 5.3
  #- hhvm
before_install:
  - cd test
  - composer require codeception/codeception:${CODECEPTION_VERSION}
  - composer update
  - mkdir tests/_log
  - php vendor/bin/codecept build

script: php vendor/bin/codecept run -d
